- hosts: client
  user: ansible
  become: true
  tasks:
    - name: Enable EPEL Repository
      yum:
        name: epel-release
        state: latest
    - name: Install borgbackup
      yum:
        name: borgbackup
        state: latest
    - name: Create a group borg
      group:
        name: borg
        state: present
    - name: Create a user borg
      user:
        name: borg
        shell: /bin/bash
        group: borg
    - name: Create a .ssh directory for borg user
      ansible.builtin.file:
        path: /home/borg/.ssh
        state: directory
        mode: '0700'
        owner: borg
        group: borg
    - name: Create a .ssh directory for root user
      ansible.builtin.file:
        path: /root/.ssh
        state: directory
        mode: '0700'
        owner: root
        group: root
    - name: Create a /var/backup
      ansible.builtin.file:
        path: /var/backup
        state: directory
        mode: '0755'
        owner: borg
        group: borg
    - name: Start a prov script to do the rest
      script:
        cmd: client/prov-client.sh
    - name: Copy borg-backup.service systemd files
      copy:
        src: client/borg-backup.service
        dest: /etc/systemd/system/borg-backup.service
    - name: Copy borg-backup.timer systemd files
      copy:
        src: client/borg-backup.timer
        dest: /etc/systemd/system/borg-backup.timer
    - name: Start and enable borg-backup timer
      systemd:
        name: borg-backup.timer
        enabled: yes
        state: started
    - name: Start and enable borg-backup service
      systemd:
        name: borg-backup.service
        enabled: yes
        state: started

