- hosts: client
  user: ansible
  become: true
  tasks:
    - name: Enable EPEL Repository
      yum:
        name: epel-release
        state: latest
    - name: Install borgbackup
      yum:
        name: borgbackup
        state: latest
    - name: Create a group borg
      group:
        name: borg
        state: present
    - name: Create a user borg
      user:
        name: borg
        shell: /bin/bash
        group: borg
    - name: Create a /var/backup
      ansible.builtin.file:
        path: /var/backup
        state: directory
        mode: '0755'
        owner: borg
        group: borg

